language: android
sudo: false
email: false
android:
  components:
    - tools
    - platform-tools
    - build-tools-27.1.1
    - android-27
    - extra

before_install:
    #Install codecov
    - pip install --user codecov

script:
    - chmod +x ./gradlew

after_success:
    #Run codecov
    - codecov
