language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-27.1.1
    - android-27
    - extra

before_install:
    - pip install --user codecov    #Install codecov

script:
    - chmod +x ./gradlew

after_success:
    - codecov                       #Run codecov
