language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-27.1.1
    - android-27
    - extra

before_install:
    - pip install --user codecov    #Install codecov

script:
    - chmod +x ./gradlew
    - ./gradlew build jacocoTestReport assembleAndroidTest

after_success:
  - bash <(curl -s https://codecov.io/bash) -t aae31d62-3dc2-4607-896c-a160d5036d20
